name: Compile LaTeX documents & deploy page

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
#   group: "pages"
#   cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
    - name: Set up LaTeX environment
      id: set-up-env
      uses: dante-ev/latex-action@2021-A
    - name: Compile thesis LaTeX file to PDF
      id: thesis-compile
      run: latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -use-make thesis.tex
    - name: Compile presentation LaTeX file to PDF
      id: presentation-compile
      run: latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -use-make slides.tex
    - name: Move PDFs to "docs/" directory
      id: move-pdf
      run: mkdir -p docs/ &&  mv thesis.pdf slides.pdf docs/
    - name: Deploy to GitHub Pages
      id: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs